# Generated by Django 5.2.1 on 2025-06-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_resolucion', models.CharField(max_length=100, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('numero_socio', models.CharField(max_length=50, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('tipo_sancion', models.CharField(choices=[('Doble Amarilla', 'Doble Amarilla'), ('Provisorio', 'Provisorio'), ('Definitiva', 'Definitiva')], default='Definitiva', max_length=50)),
                ('doble_amarilla_pagada', models.BooleanField(default=False)),
                ('fecha_pago_doble_amarilla', models.DateField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.jugador')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_liga.resolucion')),
            ],
        ),
    ]
