# Generated by Django 5.2.1 on 2025-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_liga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='resolucion',
            options={'verbose_name': 'Resolución', 'verbose_name_plural': 'Resoluciones'},
        ),
        migrations.AlterModelOptions(
            name='sancion',
            options={'verbose_name': 'Sanción', 'verbose_name_plural': 'Sanciones'},
        ),
        migrations.AddField(
            model_name='sancion',
            name='cantidad_fechas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='equipos',
        ),
        migrations.AlterModelTable(
            name='jugador',
            table='jugadores',
        ),
        migrations.AlterModelTable(
            name='resolucion',
            table='resoluciones',
        ),
        migrations.AlterModelTable(
            name='sancion',
            table='sanciones',
        ),
    ]
