# Generated by Django 5.2.1 on 2025-06-10 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_liga', '0002_alter_equipo_options_alter_jugador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='numero_socio',
        ),
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(choices=[('C33', 'Categoría C33'), ('C40', 'Categoría C40'), ('C45', 'Categoría C45')], default='C40', max_length=10),
        ),
        migrations.AddField(
            model_name='jugador',
            name='codigo_socio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Socio'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='gestion_liga.equipo'),
        ),
    ]
